config/routes.rb
Rails.application.routes.draw do  
    
  get 'events/upcoming' => 'events#upcoming', as: :upcoming

  get 'public/about' => 'public#about', as: :about

  root 'public#index'

  resources :user_sessions

  resources :users

  resources :members

  resources :events

  match '/login', :to => 'user_sessions#new', via: [:get, :post]
  match '/logout', :to => 'user_sessions#destroy', via: [:get, :post]

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.relative_url_root = ""  
  helper_method :current_user, :require_user, :mobile_device?  

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
  def require_user
    unless current_user
      flash[:alert]="Morate biti logirani da bi vidjeli podatke"
      redirect_to root_path
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  	@events = Event.where("public = ? and event_date >= ?", true, Time.now).order("event_date asc").paginate(:page => params[:page], :per_page => 3)
  	@images = Dir.glob("app/assets/images/slide/*.jpg")
  end

  def about
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'T.S. Zdenac', root_path %></li>    
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="left">
<li><%= link_to "O nama", about_path %></li>
<li><%= link_to "Kontaktirajte nas", contacts_path %></li>
</ul>
<ul class="right">
	<% if current_user %>	
	<li><%= link_to 'Nadolazeće svirke', upcoming_path %></li>
	<li><%= link_to 'Sve svirke', events_path %></li>
	<% end %>
	<% if current_user %>
	<li><%= link_to 'Odjava', logout_path %></li>
	<% else %>
	<li><%= link_to 'Prijava', login_path %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bandsite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "T.S. Zdenac" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>